spring:
 datasource:
   platform: postgres
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/UsersServiceDB
   username: postgres
   password: postgres
 jpa:
   database: POSTGRESQL
   show-sql: true
   hibernate.ddl-auto: none #create-drop
   database-platform: org.hibernate.dialect.PostgreSQL94Dialect
# liquibase:
#   enabled: true
#   change-log: /db/changelog/db-changelog-master.xml
#   drop-first: false

logging:
   level:
      root: WARN
      org.springframework.web: DEBUG
      org.hibernate: ERROR

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
   port: 8089

management:
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true 
    httptrace:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    shutdown:
      enabled: true
    liquidbase:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env, health, info, httptrace, metrics, mappings, shutdown, liquidbase, refresh